# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Ian"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:         :title.html

# Markdown
#markdown:           redcarpet  - this works better for latex but worse for bokeh plots
#markdown:           rdiscount  - supports bokeh but not easy latex
markdown:           kramdown

# Navigation
nav:
  - name:           "Github"
    href:           "//github.com/ianhi"
  - name:           "CV"
    href:           "/files/CV.pdf"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
