# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Ian"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:         :title.html

# Markdown
markdown: redcarpet

# Navigation
nav:
  - name:           "Github"
    href:           "//github.com/ianhi"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
