# Title of your blog; shows in the header
name: "ianhi"

# Description of your content (will only be used on Google Search)
description:  "The thoughts of Ian Hunt-Isaak"

# Your name. Will show in your footer + sidebar
author: "Ian Hunt-Isaak"

#url:  "http://ianhi.github.io"
baseurl:  ""
permalink: :title/


# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I'm a Physics major at Oberlin college interested in generative art and data visualization."

# Social Accounts (mine, as placeholders)
twitter:
github: ianhi
linkedin: ian-hunt-isaak-4a5498111
CV: CV.pdf
dribbble:
instagram:

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: ianhi.github.io
ga_tracking_id: UA-70410040-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty
highlighter: rouge 

paginate: 10
paginate_path: "/page/:num"

# SCSS
sass:
  sass_dir: _scss
  style: :compressed
